# SERVER
server:
    port: 7082
# EUREKA
eureka:
    client:
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: http://user:pwd@localhost:7761/eureka
    instance:
        health-check-url-path: /actuator_change_path/health
        status-page-url-path: /actuator_change_path/info
        leaseRenewalIntervalInSeconds: 3
        leaseExpirationDurationInSeconds: 10
        preferIpAddress: true
        metadataMap:
            swaggerEnabled: true
            swaggerPath: v2/api-docs
# LOG
logging:
    file:
        name: /var/log/agoero/driver-all-prod.log
# GATEWAY
gateway:
    host: www.agoero.fr/api
    protocol: http
# SWAGGER
swagger:
    display-all: true
